version: '3.2'
services:
  chart:
    image: bellcd/robinhood:pab
    depends_on:
      - mongo
    ports:
      - '4550:4550'
    links:
      - "mongo:db"
      - "mongo:database"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - '1100:27017'